$O365PropertiesUser = @()
    'UserPrincipalName',
    'SignInName',
    'DisplayName',
    'LastName',
    'FirstName',
    'Department',
    'Title',
    'ImmutableId',
    'IsLicensed',
    'Office',
    'StreetAddress',
    'City',
    'State',
    'PostalCode',
    'Country',
    'PhoneNumber',
    'MobilePhone',
    'Fax',
    @{Name='AlternateMobilePhones';Expression={$_.AlternateMobilePhones -join ";"}},
    @{Name=’AlternateEmailAddresses';Expression={$_.AlternateEmailAddresses -join ";"}},
    @{Name='ProxyAddresses';Expression={$_.ProxyAddresses -join ";"}},
    'IsBlackberryUser',
    'LastDirSyncTime',
    'LastPasswordChangeTimestamp',
    'LicenseReconciliationNeeded',
    'OverallProvisioningStatus',
    'PasswordNeverExpires',
    'PasswordResetNotRequiredDuringActivate',
    'PortalSettings',
    'PreferredLanguage',
    'ReleaseTrack',
    'SoftDeletionTimestamp',
    @{Name='StrongAuthenticationRequirements';Expression={$_.StrongAuthenticationRequirements.state}},
    'StrongPasswordRequired',
    'StsRefreshTokensValidFrom',
    'UserLandingPageIdentifierForO365Shell',
    'UserThemeIdentifierForO365Shell',
    'UserType',
    'ValidationStatus',
    'WhenCreated',
    'UsageLocation',
    @{Name='Licenses';Expression={$_.Licenses.accountskuid -join ";"}}
)