$csvfile ='L:\TeamSiteSlowness\SiteCollectionAdministrators.csv'
import-csv $csvfile | where {	

	$emailFrom = "SharePointSupport@example.com"
        # Use commas for multiple addresses
        $emailTo = $_.Administrator
        $subject = "SharePoint team site movement from one content database to another"
	$Ownername = $_.OwnerName
	$siteurl = $_.siteurl
        $body = "Hi $Ownername , `n `n   We are doing maintenance for SharePoint from <Start DateTime> to <End DateTime> . Your team site $siteurl is also part of it. 		Your SharePoint site would be unavailable for 40 minutes anytime in the above maintenace window. Please plan accordingly. `n`n This is autogenerated email. In case of any concerns, please send an email to SharePointSupport@example.com `n `nThanks, `nSharePoint Support Team."
        $smtpServer = "smtpserver.example.com"
        $smtp = new-object Net.Mail.SmtpClient($smtpServer)
        $smtp.Send($emailFrom, $emailTo, $subject, $body)
        

}